/**
 * This file is generated by vite-plugin-sveltekit-api-codegen.
 * Do not edit this file directly, it will be overwritten.
 */

export default {
    api: {
        cal: {
            /**
             * POST /api/cal
             */
            async POST(
                init?: RequestInit,
            ): Promise<{ success: boolean; result: string }> {
                return fetch(`/api/cal`, {
                    method: 'POST',
                    ...init,
                }).then((res) => res.json());
            },
        },

        getHelloworld: {
            /**
             * GET /api/getHelloworld
             */
            async GET(
                init?: RequestInit,
            ): Promise<{
                demoappApiKey: string;
                supabasePrivateKey: string;
                supabaseJWTSecret: string;
                supabaseUrl: string;
            }> {
                return fetch(`/api/getHelloworld`, {
                    method: 'GET',
                    ...init,
                }).then((res) => res.json());
            },
        },

        getResult: {
            /**
             * GET /api/getResult
             */
            async GET(init?: RequestInit): Promise<any> {
                return fetch(`/api/getResult`, {
                    method: 'GET',
                    ...init,
                }).then((res) => res.json());
            },
        },
    },
};
